share_list = 'share_list.csv'
stocks_db = 'market_database.sqlite'
base_url = 'https://archives.nseindia.com/content/historical/EQUITIES/'
p1 = 'CLOSE'
p2 = 'TOTTRDQTY'
images = 'saved_plots/'
my_user_agent = '"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"'
